apiVersion: v1
kind: Service
metadata:
  name:  fqts-rtp-service
  namespace: fqts
spec:
  type: NodePort
  selector:
    app: fqts-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000